### ISSUE TITLE
Microsoft Edge issues

### ISSUE THREAD

**Issue by inopinatus** [euvl/vue-js-toggle-button#30]
I'm just testing version 1.1.5 with Microsoft Edge 40.15063.0.0 / Microsoft EdgeHTML 15.15063 and all I'm seeing is a circle when off and nothing at all when toggled on.

Same issue just looking http://vue-js-toggle-button.yev.io/

Not sure what's wrong but it's not happy...

**Comment by volodymyrrudyi** [comment]
![image](https://user-images.githubusercontent.com/875828/31115110-b4858d28-a829-11e7-81ab-1942635d96f8.png)

**Comment by euvl** [comment]
Hey @inopinatus @volodymyrrudyi,

Thanks for reporting the issue. Clearly the problem arises from using css vars, I've pushed a branch (`no-css-vars`) where css is simplified. 

If any of you could check whether the issue is resolved in this brunch, it will help a lot ( do not have windows vm right now).
Branch: https://github.com/euvl/vue-js-toggle-button/tree/no-css-vars

Thanks
Thanks

**Comment by inopinatus** [comment]
@euvl that was fast! I just tried it in my Win10 test VM with Edge and it looks good.

**Comment by euvl** [comment]
cool, thanks! ill merge it later tonight 👍

**Comment by inopinatus** [comment]
1.2.0 looking good in Edge in my prodlike demo environment. Also bonus: seems to be working in IE11.
